package vista;

import Metodos_sql.Metodos_sql;
import modelo.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author doria
 */
public class frameLogin extends javax.swing.JFrame {

    /**
     * Creates new form frameLogin
     */
    public frameLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }
        Metodos_sql metodos = new Metodos_sql();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTitulo = new javax.swing.JLabel();
        loginNombre = new javax.swing.JLabel();
        loginPassword = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginTitulo.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        loginTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitulo.setText("LOGIN");

        loginNombre.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        loginNombre.setText("Nombre");

        loginPassword.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        loginPassword.setText("Contraseña");

        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });

        loginButton.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        loginButton.setText("Login");
        loginButton.setMaximumSize(new java.awt.Dimension(100, 35));
        loginButton.setMinimumSize(new java.awt.Dimension(100, 35));
        loginButton.setPreferredSize(new java.awt.Dimension(100, 35));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginSalir.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        loginSalir.setText("Salir");
        loginSalir.setMaximumSize(new java.awt.Dimension(100, 35));
        loginSalir.setMinimumSize(new java.awt.Dimension(100, 35));
        loginSalir.setPreferredSize(new java.awt.Dimension(100, 35));
        loginSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(loginTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(loginSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loginNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userField)
                                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(loginTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
          int userRol;
          String busqueda_usuario = metodos.buscarUsuarioRegistrado(userField.getText(), new String(passwordField.getPassword()));
          if(userField.getText().equals("root") && new String(passwordField.getPassword()).equals("root")){
              JOptionPane.showMessageDialog(this, "Bienvenido iniciaste sesion como Administrador :) ");
              framePrincipal ventana = new framePrincipal();           
              ventana.lblNombre.setText("root");
              ventana.setVisible(true);
              this.dispose();
          } else if(busqueda_usuario.equals("Usuario encontrado")){
              String busqueda_nombre = metodos.buscarNombre(userField.getText());
              userRol = metodos.getRolUsuario(busqueda_nombre);
              JOptionPane.showMessageDialog(this, "Bienvenido "+ busqueda_nombre+"y tu rol es : "+userRol);
              framePrincipal ventana = new framePrincipal();
              ventana.lblNombre.setText(busqueda_nombre);
              if(userRol == 2){//Recursos Humanos
                  ventana.initRecursosHumanos();                   
              } else if(userRol == 3){ //Administrador
                  ventana.initAdministrador();
              } else if(userRol == 1){ //Encargado de Almacenes
                  ventana.initAlmacenes();
              }
              ventana.setVisible(true);
              this.dispose();
          } else {
              JOptionPane.showMessageDialog(this, "Usuario no registrado");
              userField.setText("");
              passwordField.setText("");
          }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_loginSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginNombre;
    private javax.swing.JLabel loginPassword;
    private javax.swing.JButton loginSalir;
    private javax.swing.JLabel loginTitulo;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
