/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author Delgadillo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         this.setLocationRelativeTo(null);
         


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaa1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaa = new javax.swing.JTable();
        inventariobtn = new javax.swing.JButton();
        cajabtn = new javax.swing.JButton();
        ventasbtn = new javax.swing.JButton();
        contabilidadbtn = new javax.swing.JButton();
        nombree = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 60));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Base de Datos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 330, 60));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contrasena:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 60));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 0));
        jButton2.setText("Conectar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 170, 60));

        pid.setEditable(false);
        pid.setBackground(new java.awt.Color(102, 102, 102));
        pid.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pid.setForeground(new java.awt.Color(51, 51, 51));
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, 40));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 60));

        tablaa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaa1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 110, 160));

        tablaa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Interfaz"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaa);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 160));

        inventariobtn.setBackground(new java.awt.Color(51, 51, 51));
        inventariobtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        inventariobtn.setForeground(new java.awt.Color(102, 0, 102));
        inventariobtn.setText("Inventario");
        inventariobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventariobtnActionPerformed(evt);
            }
        });
        getContentPane().add(inventariobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 110, -1));

        cajabtn.setBackground(new java.awt.Color(51, 51, 51));
        cajabtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cajabtn.setForeground(new java.awt.Color(102, 0, 102));
        cajabtn.setText("Caja");
        cajabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajabtnActionPerformed(evt);
            }
        });
        getContentPane().add(cajabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 110, -1));

        ventasbtn.setBackground(new java.awt.Color(51, 51, 51));
        ventasbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ventasbtn.setForeground(new java.awt.Color(102, 0, 102));
        ventasbtn.setText("R-Ventas");
        ventasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ventasbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 110, -1));

        contabilidadbtn.setBackground(new java.awt.Color(51, 51, 51));
        contabilidadbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        contabilidadbtn.setForeground(new java.awt.Color(102, 0, 102));
        contabilidadbtn.setText("Contabilidad");
        contabilidadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contabilidadbtnActionPerformed(evt);
            }
        });
        getContentPane().add(contabilidadbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));
        getContentPane().add(nombree, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, 40));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 200, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/adasdasd.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       conectarDB();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void inventariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventariobtnActionPerformed
 
      
       
    }//GEN-LAST:event_inventariobtnActionPerformed

    private void cajabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajabtnActionPerformed
    
    }//GEN-LAST:event_cajabtnActionPerformed

    private void contabilidadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contabilidadbtnActionPerformed
    
    }//GEN-LAST:event_contabilidadbtnActionPerformed

    private void ventasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasbtnActionPerformed
     
    }//GEN-LAST:event_ventasbtnActionPerformed

 public Connection conectarDB(){

     //Statement  at = null;
    String cadena = "jdbc:postgresql://"+ip+":"+puerto+"/"+db;
    
        try {
            Class.forName("org.postgresql.Driver");
            Conexion = DriverManager.getConnection(cadena,"postgres","Delgadillo");
          //JOptionPane.showMessageDialog(null, "Se conecto");
          
           Validar();
            
        }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Error al conectar"+e.toString());
       }   
       
      
           // nombree.setText("");
          // pass.setText("") ;
          
        return Conexion;
    }
    
    /*public void Validarr(){
        Statement  at = null;        
         try {
             at = Conexion.createStatement();
             String nombreeee=nombree.getText();
             String passss=pass.getText();
            ResultSet rs = at.executeQuery("select verificarusuario('"+nombreeee+"','"+passss+"')");
            while (rs.next()){
                String piddd;
                piddd= rs.getString("verificarusuario");

                System.out.println(piddd);
            }
        
            rs.close();
            at.close();
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
        }                                        
        
    
    }  */
   
    public void Validar(){
            
        Statement  at = null;
         String usuario = nombree.getText();
        String contrasena = pass.getText();
        
         try {
             at = Conexion.createStatement();
            ResultSet rs = at.executeQuery("select verificarusuario('"+usuario+"','"+contrasena+"');");
            while (rs.next()){
                String validador;
               validador= rs.getString("verificarusuario");
               
                if (validador.equals("true")) {
                    
                    JOptionPane.showMessageDialog(null, "Se conecto correctamente");
                     PID();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error al conectar,Usuario o Contrasena incorrectos");
                       nombree.setText("");
                       pass.setText("") ;
                }
            }
          
            rs.close();
            at.close();
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Error al conectar,Usuario o Contrasena incorrectos"+e.toString());
        }                                        
        
    
    }
    
    
        public void PID(){
        Statement  at = null;        
         try {
             at = Conexion.createStatement();
            ResultSet rs = at.executeQuery("select pg_backend_pid();");
            while (rs.next()){
                String pidd;
                pidd= rs.getString("pg_backend_pid");

                pid.setText(pidd);
                 presentarIU();
                    presentarIUN();
                    mostrarinterfaz();
            }
        
            rs.close();
            at.close();
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
        }                                        
        
    
    }    
    
        
void presentarIU(){
     Statement  at = null;
      DefaultTableModel modelo = new DefaultTableModel();
  modelo.addColumn("Interfaz");
 // modelo.addColumn("Nombre");  
  //modelo.addColumn("Precio");
  //modelo.addColumn("Tiempo");
  tablaa.setModel(modelo);
  DefaultComboBoxModel combo = new DefaultComboBoxModel();
 String datos[] = new String[1];

        try {
             at = Conexion.createStatement();
          
            ResultSet rs = at.executeQuery("Select IU_USUARIO('" +nombree.getText()+"')");
            while (rs.next()){
                datos[0]= rs.getString("iu_usuario");
                    /*if(datos[0] == "1"){
                         new Inventarios().setVisible(true);
                    }*/
                 
                //datos[1]= rs.getString("nombre");
               // datos[2]= rs.getString("precio");
               // datos[3]= rs.getString("tiempo");
                modelo.addRow(datos); 
            }
           // JOptionPane.showMessageDialog(null, "Acepta para continuar");
            rs.close();
            at.close();
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
        }
        
        
        
       // System.out.println(tablaa.getValueAt(0, 0).toString()); //filas t columnas
    }     
void presentarIUN(){
     Statement  at = null;
      DefaultTableModel modelo = new DefaultTableModel();
  modelo.addColumn("Nombre");
 // modelo.addColumn("Nombre");  
  //modelo.addColumn("Precio");
  //modelo.addColumn("Tiempo");
  tablaa1.setModel(modelo);
  DefaultComboBoxModel combo = new DefaultComboBoxModel();
 String datos[] = new String[4];

        try {
             at = Conexion.createStatement();
          
            ResultSet rs = at.executeQuery("Select I_Nombre('" +nombree.getText()+"')");
            while (rs.next()){
                datos[0]= rs.getString("i_nombre");
                //datos[1]= rs.getString("nombre");
               // datos[2]= rs.getString("precio");
               // datos[3]= rs.getString("tiempo");
                modelo.addRow(datos); 
            }
           // JOptionPane.showMessageDialog(null, "Acepta para continuar");
            rs.close();
            at.close();
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
        }
    }
void mostrarinterfaz(){
    
               inventariobtn.setEnabled(false); 
           ventasbtn.setEnabled(false); 
           cajabtn.setEnabled(false); 
           contabilidadbtn.setEnabled(false); 
    
int cols = tablaa.getColumnCount();
int fils = tablaa.getRowCount();
for(int i=0; i<fils; i++) {
for(int j=0; j<cols; j++){
    String valor=tablaa.getValueAt(i, j).toString();
        if ("1".equals(valor) ) {
       // new Inventarios().setVisible(true);
       inventariobtn.setEnabled(true);      
        }
        if ("2".equals(valor) ) {
       contabilidadbtn.setEnabled(true);      
        }
        if ("3".equals(valor) ) {
       cajabtn.setEnabled(true);      
        }
        if ("8".equals(valor) ) {
       ventasbtn.setEnabled(true);      
        }
//System.out.println(tablaa.getValueAt(i, j).toString());

}
}

    
}
        
        
        
   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cajabtn;
    private javax.swing.JButton contabilidadbtn;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton inventariobtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextField nombree;
    public static javax.swing.JPasswordField pass;
    public static javax.swing.JTextField pid;
    private javax.swing.JTable tablaa;
    private javax.swing.JTable tablaa1;
    private javax.swing.JButton ventasbtn;
    // End of variables declaration//GEN-END:variables
        
    
    //String usuarioooo = "postgres";
   // String contrasenaaaa = "Delgadillo";
    String db = "TABLAAAAAAA";
    String ip = "localhost";
    String puerto = "5432";
    Connection Conexion = null;
}
